[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remapping = []

# Allow writing to deployments.env file
fs_permissions = [
    { access = "write", path = "./deployments.env" }
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
